# Generated by Django 5.2.1 on 2025-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_profiles_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('💪', 'Working Out'), ('🏃', 'Running'), ('🧘', 'Meditating'), ('🥗', 'Eating Healthy'), ('😴', 'Resting'), ('🎯', 'Focused'), ('🌟', 'Feeling Great'), ('🔋', 'Low Energy'), ('🎮', 'Taking a Break'), ('📚', 'Learning')], default='🌟', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
