# Generated by Django 5.2.1 on 2025-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_pics/default-avatar.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='cover_pics/default-cover.jpg', upload_to='cover_pics'),
        ),
    ]
