# Generated by Django 5.2.1 on 2025-05-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_add_mptt_fields'),
        ('community', '0003_blogpost_likes_forumpost_likes_thread_likes_and_more'),
    ]

    operations = [
    ]
