# Generated by Django 5.2.1 on 2025-05-29 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_merge_20250529_2123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['tree_id', 'lft']},
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forum_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
